# Comprehensive cleanup script for portfolio
$ErrorActionPreference = "Stop"

$yourName = "BELYAGOUBIABDELILAH"
$yourGithub = "https://github.com/BELYAGOUBIABDELILAH"
$yourRepo = "https://github.com/BELYAGOUBIABDELILAH/30-days-of-data-analyst-.git"

Write-Host "Starting comprehensive cleanup..." -ForegroundColor Cyan

# Function to clean content
function Clean-Content {
    param($content)
    
    # Replace author names
    $content = $content -replace "HARSHKUMAR65", $yourName
    $content = $content -replace "harsh kumar|Harsh Kumar|HARSH KUMAR", $yourName
    $content = $content -replace "harshkumar65", $yourName
    
    # Replace GitHub links
    $content = $content -replace "github\.com/HARSHKUMAR65", "github.com/$yourName"
    $content = $content -replace "github\.com/harshkumar65", "github.com/$yourName"
    
    # Replace repository URLs
    $content = $content -replace "https://github\.com/HARSHKUMAR65/30-days-of-data-analyst-\.git", $yourRepo
    
    # Remove Kaggle references
    $content = $content -replace "\[.*?kaggle\.com.*?\]\(.*?\)", ""
    $content = $content -replace "https?://.*?kaggle\.com\S+", ""
    
    # Remove Google Colab references
    $content = $content -replace "https?://colab\.research\.google\.com\S+", ""
    $content = $content -replace "Automatically generated by Colaboratory\.", ""
    $content = $content -replace "Original file is located at.*", ""
    
    # Remove external challenge links
    $content = $content -replace "\[.*?challenge.*?\]\(.*?\)", ""
    $content = $content -replace "https?://.*?challenge\S+", ""
    
    return $content
}

# Clean all README files in day folders
Write-Host "`nCleaning README files..." -ForegroundColor Yellow
$readmes = Get-ChildItem -Path "Day *" -Recurse -Filter "README.md"
foreach ($readme in $readmes) {
    $content = Get-Content $readme.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    if ($content) {
        $originalContent = $content
        $content = Clean-Content $content
        
        # Update README structure with professional format
        if ($content -notmatch "Author.*BELYAGOUBIABDELILAH") {
            $content = $content -replace "\*\*Author:.*", "**Author:** [$yourName]($yourGithub)"
            $content = $content -replace "Created by.*", "*Created by [$yourName]($yourGithub)*"
        }
        
        if ($content -ne $originalContent) {
            Set-Content -Path $readme.FullName -Value $content -Encoding UTF8 -NoNewline
            Write-Host "  Updated: $($readme.FullName)" -ForegroundColor Green
        }
    }
}

# Clean all Jupyter notebooks
Write-Host "`nCleaning Jupyter notebooks..." -ForegroundColor Yellow
$notebooks = Get-ChildItem -Path "Day *" -Recurse -Filter "*.ipynb"
foreach ($notebook in $notebooks) {
    $content = Get-Content $notebook.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    if ($content) {
        $originalContent = $content
        $content = Clean-Content $content
        
        if ($content -ne $originalContent) {
            Set-Content -Path $notebook.FullName -Value $content -Encoding UTF8 -NoNewline
            Write-Host "  Updated: $($notebook.FullName)" -ForegroundColor Green
        }
    }
}

# Clean SQL files
Write-Host "`nCleaning SQL files..." -ForegroundColor Yellow
$sqlFiles = Get-ChildItem -Path "Day *" -Recurse -Filter "*.sql"
foreach ($sqlFile in $sqlFiles) {
    $content = Get-Content $sqlFile.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    if ($content) {
        $originalContent = $content
        $content = Clean-Content $content
        
        if ($content -ne $originalContent) {
            Set-Content -Path $sqlFile.FullName -Value $content -Encoding UTF8 -NoNewline
            Write-Host "  Updated: $($sqlFile.FullName)" -ForegroundColor Green
        }
    }
}

# Remove useless files
Write-Host "`nRemoving unnecessary files..." -ForegroundColor Yellow
$uselessPatterns = @(
    "*.log",
    "*.py",
    "*checkpoint*",
    "untitled*",
    "Untitled*",
    "clean_data*",
    "*.pbit",
    "*.pdf"
)

foreach ($pattern in $uselessPatterns) {
    $files = Get-ChildItem -Path "Day *" -Recurse -Filter $pattern -File -ErrorAction SilentlyContinue
    foreach ($file in $files) {
        # Keep Day-7.ipynb related Python file
        if ($file.Name -eq "day_7.py") {
            continue
        }
        Remove-Item $file.FullName -Force
        Write-Host "  Removed: $($file.FullName)" -ForegroundColor Red
    }
}

# Remove .ipynb_checkpoints folders
$checkpoints = Get-ChildItem -Path "Day *" -Recurse -Directory -Filter ".ipynb_checkpoints" -ErrorAction SilentlyContinue
foreach ($checkpoint in $checkpoints) {
    Remove-Item $checkpoint.FullName -Recurse -Force
    Write-Host "  Removed checkpoint: $($checkpoint.FullName)" -ForegroundColor Red
}

Write-Host "`n--- Cleanup complete! ---" -ForegroundColor Green
